services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Supabase DB credentials — dummy placeholders (set real values in Render dashboard)
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: your_db_name
      - key: DB_POSTGRESDB_HOST
        value: your_host.supabase.co
      - key: DB_POSTGRESDB_USER
        value: your_db_user
      - key: DB_POSTGRESDB_PASSWORD
        value: your_db_password
      - key: DB_POSTGRESDB_PORT
        value: "5432"

      # Enable and auto-install community nodes
      - key: N8N_COMMUNITY_PACKAGES_ENABLED
        value: "true"
      - key: N8N_CUSTOM_EXTENSIONS
        value: "@apify/n8n-nodes-apify.apify"  # Replace with actual package names
