services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Supabase DB credentials — set values in the Render dashboard
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
      - key: DB_POSTGRESDB_HOST
      - key: DB_POSTGRESDB_USER
      - key: DB_POSTGRESDB_PASSWORD
      - key: DB_POSTGRESDB_PORT
        value: "5432"

      # Community nodes — auto-installed on each startup
      - key: N8N_COMMUNITY_PACKAGES_ENABLED
        value: "true"
      - key: N8N_CUSTOM_EXTENSIONS
        value: "@apify/n8n-nodes-apify.apify"  # Replace with actual package names
